export type DetailedError =
  | 'TODO_FETCH_FAILED'
  | 'TODO_FETCH_BY_ID_FAILED'
  | 'TODO_CREATE_FAILED'
  | 'TODO_UPDATE_FAILED'
  | 'TODO_DELETE_FAILED'
  | 'NOT_FOUND_ID_IN_TOGGLE'
  | 'NOT_FOUND_ID_IN_UPDATE'
  | 'EMPTY_CONTENT';
